name       : xcb-util-xrm
version    : '1.3'
release    : 4
source     :
    - https://github.com/Airblader/xcb-util-xrm/releases/download/v1.3/xcb-util-xrm-1.3.tar.gz : 0129f74c327ae65e2f4ad4002f300b4f02c9aff78c00997f1f1c5a430f922f34
license    : MIT
component  : xorg.apps
summary    : XCB utility functions for the X resource manager
description: |
    The XCB util modules provides a number of libraries which sit on top of libxcb, the core X protocol library, and some of the extension libraries.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
