name       : xcb-util-xrm
version    : 1.0
release    : 1
source     :
    - https://github.com/Airblader/xcb-util-xrm/releases/download/v1.0/xcb-util-xrm-1.0.tar.bz2 : 9400ac1ecefdb469b2f6ef6bf0460643b6c252fb8406e91377b89dd12eefbbc0
license    : MIT
component  : xorg.apps
summary    : XCB utility functions for the X resource manager
description: |
    The XCB util modules provides a number of libraries which sit on top of libxcb, the core X protocol library, and some of the extension libraries.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb-util)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
